import { genreIdMap } from "./genre-id-map";

export type GenreMenuItem = {
    id: string;
    name: string;
};

export type GenreMenuGroup = {
    title: string;
    items: GenreMenuItem[];
};

// 👇 ID取得関数（ここ重要）
function getId(name: string): string {
    return genreIdMap[name] || "";
}

export const genreGroups: GenreMenuGroup[] = [
    {
        title: "シチュエーション",
        items: [
            { name: "アイドル・芸能人", id: getId("アイドル・芸能人") },
            { name: "美少女", id: getId("美少女") },
            { name: "巨乳", id: getId("巨乳") },
            { name: "単体作品", id: getId("単体作品") },
            { name: "ドキュメンタリー", id: getId("ドキュメンタリー") },
            { name: "デビュー作品", id: getId("デビュー作品") },
            { name: "中出し", id: getId("中出し") },
            { name: "アクメ・オーガズム", id: getId("アクメ・オーガズム") },
            { name: "ハイビジョン", id: getId("ハイビジョン") },
            { name: "4K", id: getId("4K") },
            { name: "独占配信", id: getId("独占配信") },
            { name: "M女", id: getId("M女") },
            { name: "淫乱・ハード系", id: getId("淫乱・ハード系") },
            { name: "4時間以上作品", id: getId("4時間以上作品") },
            { name: "ハメ撮り", id: getId("ハメ撮り") },
            { name: "妄想族", id: getId("妄想族") },
            { name: "素人", id: getId("素人") },
            { name: "顔射", id: getId("顔射") },
            { name: "主観", id: getId("主観") },
            { name: "パイズリ", id: getId("パイズリ") },
            { name: "スレンダー", id: getId("スレンダー") },
            { name: "拘束", id: getId("拘束") },
            { name: "ぶっかけ", id: getId("ぶっかけ") },
            { name: "盗撮・のぞき", id: getId("盗撮・のぞき") },
            { name: "女子校生", id: getId("女子校生") },
            { name: "制服", id: getId("制服") },
            { name: "貧乳・微乳", id: getId("貧乳・微乳") },
            { name: "潮吹き", id: getId("潮吹き") },
            { name: "素人ホイホイ/妄想族", id: getId("素人ホイホイ/妄想族") },
            { name: "キス・接吻", id: getId("キス・接吻") },
            { name: "汗だく", id: getId("汗だく") },
            { name: "騎乗位", id: getId("騎乗位") },
            { name: "ローション・オイル", id: getId("ローション・オイル") },
            { name: "エステ", id: getId("エステ") },
            { name: "16時間以上作品", id: getId("16時間以上作品") },
            { name: "セット商品", id: getId("セット商品") },
            { name: "フェラ", id: getId("フェラ") },
            { name: "ハイクオリティVR", id: getId("ハイクオリティVR") },
            { name: "8KVR", id: getId("8KVR") },
            { name: "VR専用", id: getId("VR専用") },
            { name: "淫語", id: getId("淫語") },
            { name: "ベスト・総集編", id: getId("ベスト・総集編") },
            { name: "3P・4P", id: getId("3P・4P") },
            { name: "熟女", id: getId("熟女") },
            { name: "お風呂", id: getId("お風呂") },
            { name: "放尿・お漏らし", id: getId("放尿・お漏らし") },
            { name: "SOD素人", id: getId("SOD素人") },
            { name: "辱め", id: getId("辱め") },
            { name: "デート", id: getId("デート") },
            { name: "AI生成作品", id: getId("AI生成作品") },
            { name: "手コキ", id: getId("手コキ") },
            { name: "おもちゃ", id: getId("おもちゃ") },
            { name: "ミニ系", id: getId("ミニ系") },
            { name: "温泉", id: getId("温泉") },
            { name: "ドラマ", id: getId("ドラマ") },
            { name: "寝取り・寝取られ・NTR", id: getId("寝取り・寝取られ・NTR") },
            { name: "巨乳フェチ", id: getId("巨乳フェチ") },
            { name: "OL", id: getId("OL") },
            { name: "脚フェチ", id: getId("脚フェチ") },
            { name: "パンスト・タイツ", id: getId("パンスト・タイツ") },
            { name: "尻フェチ", id: getId("尻フェチ") },
            { name: "巨尻", id: getId("巨尻") },
            { name: "人妻・主婦", id: getId("人妻・主婦") },
            { name: "不倫", id: getId("不倫") },
            { name: "ボンテージ", id: getId("ボンテージ") },
            { name: "女捜査官", id: getId("女捜査官") },
            { name: "競泳・スクール水着", id: getId("競泳・スクール水着") },
            { name: "女上司", id: getId("女上司") },
            { name: "水着", id: getId("水着") },
            { name: "痴女", id: getId("痴女") },
            { name: "オナサポ", id: getId("オナサポ") },
            { name: "お姉さん", id: getId("お姉さん") },
            { name: "義母", id: getId("義母") },
            { name: "コスプレ", id: getId("コスプレ") },
            { name: "女子大生", id: getId("女子大生") },
            { name: "イタズラ", id: getId("イタズラ") },
            { name: "ナンパ", id: getId("ナンパ") },
            { name: "デジモ", id: getId("デジモ") },
            { name: "超乳", id: getId("超乳") },
            { name: "企画", id: getId("企画") },
            { name: "着エロ", id: getId("着エロ") },
            { name: "即ハメ", id: getId("即ハメ") },
            { name: "レズビアン", id: getId("レズビアン") },
            { name: "姉・妹", id: getId("姉・妹") },
            { name: "ハーレム", id: getId("ハーレム") },
            { name: "学生服", id: getId("学生服") },
            { name: "ファン感謝・訪問", id: getId("ファン感謝・訪問") },
            { name: "乱交", id: getId("乱交") },
            { name: "福袋", id: getId("福袋") },
            { name: "M男", id: getId("M男") },
            { name: "処女", id: getId("処女") },
            { name: "美乳", id: getId("美乳") },
            { name: "マッサージ・リフレ", id: getId("マッサージ・リフレ") },
            { name: "指マン", id: getId("指マン") },
            { name: "レズキス", id: getId("レズキス") },
            { name: "クンニ", id: getId("クンニ") },
            { name: "飲み会・合コン", id: getId("飲み会・合コン") },
            { name: "家庭教師", id: getId("家庭教師") },
            { name: "アナル", id: getId("アナル") },
            { name: "妄想", id: getId("妄想") },
            { name: "秘書", id: getId("秘書") },
            { name: "カップル", id: getId("カップル") },
            { name: "恋愛", id: getId("恋愛") },
            { name: "看護婦・ナース", id: getId("看護婦・ナース") },
            { name: "キャバ嬢・風俗嬢", id: getId("キャバ嬢・風俗嬢") },
            { name: "ランジェリー", id: getId("ランジェリー") },
            { name: "ごっくん", id: getId("ごっくん") },
            { name: "罵倒", id: getId("罵倒") },
            { name: "ギャル", id: getId("ギャル") },
            { name: "羞恥", id: getId("羞恥") },
            { name: "近親相姦", id: getId("近親相姦") },
            { name: "お母さん", id: getId("お母さん") },
            { name: "原作コラボ", id: getId("原作コラボ") },
            { name: "ディルド", id: getId("ディルド") },
            { name: "オナニー", id: getId("オナニー") },
            { name: "女優ベスト・総集編", id: getId("女優ベスト・総集編") },
            { name: "メイド", id: getId("メイド") },
            { name: "アナルセックス", id: getId("アナルセックス") },
            { name: "レオタード", id: getId("レオタード") },
            { name: "その他フェチ", id: getId("その他フェチ") },
            { name: "格闘家", id: getId("格闘家") },
            { name: "アスリート", id: getId("アスリート") },
            { name: "スポーツ", id: getId("スポーツ") },
            { name: "野外・露出", id: getId("野外・露出") },
            { name: "日焼け", id: getId("日焼け") },
            { name: "インストラクター", id: getId("インストラクター") },
            { name: "職業色々", id: getId("職業色々") },
            { name: "局部アップ", id: getId("局部アップ") },
            { name: "デカチン・巨根", id: getId("デカチン・巨根") },
            { name: "ウェイトレス", id: getId("ウェイトレス") },
            { name: "ホテル", id: getId("ホテル") },
            { name: "受付嬢", id: getId("受付嬢") },
            { name: "スチュワーデス", id: getId("スチュワーデス") },
            { name: "旅行", id: getId("旅行") },
            { name: "和服・浴衣", id: getId("和服・浴衣") },
            { name: "女将・女主人", id: getId("女将・女主人") },
            { name: "幼なじみ", id: getId("幼なじみ") },
            { name: "お爺ちゃん", id: getId("お爺ちゃん") },
            { name: "お嬢様・令嬢", id: getId("お嬢様・令嬢") },
            { name: "オタク", id: getId("オタク") },
            { name: "覆面・マスク", id: getId("覆面・マスク") },
            { name: "童貞", id: getId("童貞") },
            { name: "イラマチオ", id: getId("イラマチオ") },
            { name: "ぽっちゃり", id: getId("ぽっちゃり") },
            { name: "お婆ちゃん", id: getId("お婆ちゃん") },
            { name: "叔母さん", id: getId("叔母さん") },
            { name: "お姫様", id: getId("お姫様") },
            { name: "縛り・緊縛", id: getId("縛り・緊縛") },
            { name: "女教師", id: getId("女教師") },
            { name: "孕ませ", id: getId("孕ませ") },
            { name: "女戦士", id: getId("女戦士") },
            { name: "カーセックス", id: getId("カーセックス") },
            { name: "チャイナドレス", id: getId("チャイナドレス") },
            { name: "逆ナン", id: getId("逆ナン") },
            { name: "めがね", id: getId("めがね") },
            { name: "キャンギャル", id: getId("キャンギャル") },
            { name: "くノ一", id: getId("くノ一") },
            { name: "極道・任侠", id: getId("極道・任侠") },
            { name: "男の潮吹き", id: getId("男の潮吹き") },
            { name: "コンパニオン", id: getId("コンパニオン") },
            { name: "時間停止", id: getId("時間停止") },
            { name: "ファンタジー", id: getId("ファンタジー") },
            { name: "鬼畜", id: getId("鬼畜") },
            { name: "パイパン", id: getId("パイパン") },
            { name: "女医", id: getId("女医") },
            { name: "女王様", id: getId("女王様") },
            { name: "SM", id: getId("SM") },
            { name: "女子アナ", id: getId("女子アナ") },
            { name: "ショタ", id: getId("ショタ") },
            { name: "白目・失神", id: getId("白目・失神") },
            { name: "スワッピング・夫婦交換", id: getId("スワッピング・夫婦交換") },
            { name: "性転換・女体化", id: getId("性転換・女体化") },
            { name: "セレブ", id: getId("セレブ") },
            { name: "チアガール", id: getId("チアガール") },
            { name: "バック", id: getId("バック") },
            { name: "電マ", id: getId("電マ") },
        ],
    },
];