import { labelIdMap } from "./label-id-map";

function getId(name: string): string {
    return labelIdMap[name] || "";
}

export const labelGroups = [
    {
        title: "人気レーベル",
        items: [
            { name: "S1 NO.1 STYLE", id: getId("S1 NO.1 STYLE") },
        ],
    },

    {
        title: "その他",
        items: [
            { name: "素人ホイホイ/妄想族", id: getId("素人ホイホイ/妄想族") },
            { name: "S1 NO.1 STYLE", id: getId("S1 NO.1 STYLE") },
            { name: "MOODYZ DIVA", id: getId("MOODYZ DIVA") },
            { name: "脱ぐのは恥だがペニス立つ", id: getId("脱ぐのは恥だがペニス立つ") },
            { name: "パコ撮り", id: getId("パコ撮り") },
            { name: "マジックミラー号", id: getId("マジックミラー号") },
            { name: "S1 VR", id: getId("S1 VR") },
            { name: "GLORY QUEST", id: getId("GLORY QUEST") },
            { name: "SOD素人", id: getId("SOD素人") },
            { name: "SODVR", id: getId("SODVR") },
            { name: "エレガンス", id: getId("エレガンス") },
            { name: "OL", id: getId("OL") },
            { name: "SOD女子社員", id: getId("SOD女子社員") },
            { name: "Madonna", id: getId("Madonna") },
            { name: "----", id: getId("----") },
            { name: "MOODYZ VR", id: getId("MOODYZ VR") },
            { name: "MadonnaVR", id: getId("MadonnaVR") },
            { name: "ティッシュ", id: getId("ティッシュ") },
            { name: "kawaii* VR", id: getId(" kawaii* VR") },
            { name: "IP-VR", id: getId("IP-VR") },
            { name: "本中-VR", id: getId("本中-VR") },
            { name: "ダスッ！", id: getId("ダスッ！") },
            { name: "KMPVR-彩-", id: getId("KMPVR-彩-") },
            { name: "東京HAPPENSGATE", id: getId("東京HAPPENSGATE") },
            { name: "ACHIJO（アチージョ）", id: getId("ACHIJO（アチージョ") },
            { name: "もぎたて", id: getId("もぎたて") },
            { name: "ROCKET", id: getId("ROCKET") },
            { name: "Marrion Group VR", id: getId("Marrion Group VR") },
            { name: "アリスJAPAN", id: getId("アリスJAPAN") },
            { name: "大人のドラマ", id: getId("大人のドラマ") },
            { name: "まんきつ", id: getId("まんきつ") },
            { name: "WANZ", id: getId("WANZ") },
            { name: "SODSTAR", id: getId("SODSTAR") },
            { name: "Fitch肉感VR", id: getId("Fitch肉感VR") },
            { name: "はじめ企画", id: getId("はじめ企画") },
            { name: "アイデアポケットBEST", id: getId("アイデアポケットBEST") },
            { name: "IROKE", id: getId("IROKE") },
            { name: "DOC ERO VR", id: getId("DOC ERO VR") },
            { name: "DEEP’S", id: getId("DEEP’S") },
            { name: "HHHグループ", id: getId("HHHグループ") },
            { name: "DAHLIA", id: getId("DAHLIA") },
            { name: "ふぇち党", id: getId("ふぇち党") },
            { name: "裸婦趣向", id: getId("裸婦趣向") },
            { name: "SYUCHI", id: getId("SYUCHI") },
            { name: "えろばな。", id: getId("えろばな。") },
            { name: "卍GROUP", id: getId("卍GROUP") },
            { name: "即ヌキ", id: getId("即ヌキ") },
            { name: "誘女", id: getId("誘女") },
            { name: "溜池ゴロー", id: getId("溜池ゴロー") },
            { name: "みんなのキカタン", id: getId("みんなのキカタン") },
            { name: "本中", id: getId("本中") },
            { name: "ChuChuGirl（チュチュガール）", id: getId("ChuChuGirl（チュチュガール") },
            { name: "無垢", id: getId("無垢") },
            { name: "Nadeshiko", id: getId("Nadeshiko") },
            { name: "ルーナ旬香舎", id: getId("ルーナ旬香舎") },
            { name: "秋のシコシコ強化月間", id: getId("秋のシコシコ強化月間") },
            { name: "ブラックドッグ", id: getId("ブラックドッグ") },
            { name: "ハラスメント", id: getId("ハラスメント") },
            { name: "COSCRAFT", id: getId("COSCRAFT") },
            { name: "FALENO star", id: getId("FALENO star") },
            { name: "Hi- TMA", id: getId("Hi - TMA") },
            { name: "S級素人- ex - ", id: getId("S級素人 - ex - ") },
            { name: "グローバルメディアライト", id: getId("グローバルメディアライト") },
            { name: "V& R PLANNING", id: getId("V & R PLANNING") },
            { name: "VIVID（ドリームチケット）", id: getId("VIVID（ドリームチケット）") },
            { name: "in mad", id: getId("in mad") },
            { name: "SENZ", id: getId("SENZ") },
            { name: "CRYSTAL VR", id: getId("CRYSTAL VR") },

        ],
    },
];